config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)
  root 'restaurants#index'
  delete 'carts/clear' => 'carts#clear'
  resources :restaurants, only: [:index, :show]
  resources :dishes
  resources :carts
  resources :line_items
  resources :types
  resources :categories
end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    user.is_admin?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  # belongs_to :dish
  has_many :line_items, dependent: :destroy

  def add_dish(dish_id)
    current_dish = line_items.find_by(dish_id: dish_id)
    if current_dish
      current_dish.quantity += 1
    else
      current_dish = line_items.build(dish_id: dish_id)
    end
    current_dish
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :dishes
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :restaurant
  has_one_attached :photo
  # has_many :carts
  has_many :line_items, dependent: :destroy
  belongs_to :category

  before_destroy :ensure_not_referenced_by_any_line_item

  private
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'существуют товарные позиции')
      return false
    end
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :dish
  belongs_to :cart

  def total_price
    dish.price * quantity
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :dishes
  has_one_attached :picture
  belongs_to :type
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :restaurants
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create]

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_path,
                                notice: 'Теперь ваша корзина пуста!' }
      format.json { head :no_content }
    end
  end

  private
  def cart_params
    params.require(:cart).permit(:dish_id, :quantity)
  end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  extend ActiveSupport::Concern
  private
  def set_cart
    @cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:show]
  def index
    @dishes = Dish.all
  end

  def show
    @dish = Dish.find(params[:id])
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create]

  def create
  @restaurant = Restaurant.find(params[:restaurant])
  dish = Dish.find(params[:dish_id])
  @line_item = @cart.add_dish(dish.id)
    if @line_item.save
      flash[:notice] = 'Line item was successfully created.'
      redirect_to @restaurant
    end
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  include CurrentCart
  before_action :set_cart
  def index
    @restaurants = Restaurant.all
     @types = Type.all
     @categories = Category.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @dishes = @restaurant.dishes
    @types = Type.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def add_dish(dish_id)
    current_dish = line_items.find_by(dish_id: dish_id)
    if current_dish
      current_dish.quantity += 1
    else
      current_dish = line_items.build(dish_id: dish_id)
    end
    current_dish
  end

  def get_category_name(category)
    category = Category.find(category)
    return category.name
  end
end

app/helpers/carts_helper.rb
module CartsHelper

  def total_price(item)
    @cart = []
    @cart << item.dish.price * item.quantity
    @total_price = item.dish.price * item.quantity
    # p @cart
  end

  def total_price_cart
    Cart.all.to_a.sum { |item| total_price(item)}
  end
end

app/views/carts/_cart.html.slim
.cart
	h2.text-center Корзина

	table
        / - if @cart
        - @cart.line_items.each do |item|
            tr
                td
                    => item.dish.name
                td
                    'x
                    => item.quantity
                td
                    '=
                    = item.total_price
            br
	hr
	/ - if @cart.present?
	h5.text-center Итого: $ #{@cart.total_price}
	.text-center
        = button_to 'Очистить корзину', @cart, method: :delete, data: {confirm: 'Are you sure?'}
	    / - else
	    / .text-center.text-danger
		 /    p Корзина пуста

app/views/carts/clear.js.erb
$("#cart").html("<%= j render 'carts/cart' %>");

app/views/carts/create.js.erb
$("#cart").html("<%= j render 'carts/cart' %>");

app/views/carts/destroy.js.erb
$("#cart").html("<%= j render 'carts/cart' %>");

app/views/carts/show.html.erb
  <table>
    <% @cart.line_items.each do |item| %>
      <tr>
        <td><%= item.quantity %>&times;</td>
        <td><%= item.dish.name %></td>
        <td class="item_price"><%= number_to_currency(item.total_price) %></td>
      </tr>
    <% end %>
    <tr class="total_line">
      <td colspan="2">Total</td>
      <td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
    </tr>
  </table>
<%= button_to 'Empty cart', @cart, method: :delete,
              data: { confirm: 'Are you sure?' } %>

app/views/dishes/index.html.slim
section class="list-dishes"
	.container
		.row
			.col-md-2
			- @dishes.each do |d|
				- if d.photo.attached?
					= link_to dish_path(d) do
						= image_tag d.photo, size: '150', class:"ml-3"
				= button_to "Add to Cart", carts_path(dish_id: d), method: :post, remote: true
				

app/views/dishes/show.html.slim
section class="show"
	.container
		=> link_to 'Главная', restaurants_path
		'>
		=> link_to restaurant_path(@dish.restaurant_id) do
			= @dish.restaurant.name
		h2 #{@dish.name}
		.row
			.col-md-4
				= image_tag @dish.photo, size: '150'
			.col-md-8
				br
				br
				= @dish.name
				br
				br
				= @dish.description

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homework58</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header></header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <div class="row">
        <div class="col-md-10">
          <%= yield %>
        </div>
      
        <div class="col-md-2">
          <% if params[:controller] == 'restaurant' %>
            <%= render 'partials/menu' %>
          <% end %>
          <div id="cart">
            <%= render 'carts/cart' %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/partials/_menu.html.slim
.menu
	h2 Типы заведений
	ul class="nav nav-pills nav-staked"
		- @types.each do |type|
			li class='nav-item'
				= link_to type.name, type_path(type), class:'nav-link'

app/views/restaurants/index.html.slim
br
h2 Пункты питания
.row
	- @restaurants.each do |r|
		.card.m-3 style="width: 12rem;"
			- if r.picture.attached?
				= link_to restaurant_path(r) do
					= image_tag r.picture, size: '150', class:"card-img-top"
				.card-body.text-center
					= r.name
				

app/views/restaurants/show.html.slim
- if notice
p id="notice"
  = notice
section class="show"
	.container
		=> link_to 'Главная', restaurants_path
		'>
		= @restaurant.name
		h2 #{@restaurant.name}
		.row
			.col-md-4
				= image_tag @restaurant.picture, size: '150'
			.col-md-8
				br
				br
				= @restaurant.name
				br
				br
				= @restaurant.description
		br
		h2 Блюда данного пункта питания
		- @dishes.group_by(&:category_id).each do |category, dishes|
			= get_category_name(category)
			.row
				- dishes.each do |dish|
					.card.m-4 style="width: 12rem;"
						- if dish.photo.attached?
							= link_to dish_path(dish) do
								= image_tag dish.photo, size: '150', class:"card-img-top"
							.card-body.text-center
								.card-title
									h5 #{dish.name}
								= button_to 'В корзину', line_items_path(dish_id: dish, restaurant: @restaurant), method: :post
				